apiVersion: apps/v1
kind: Deployment
metadata:
  name: webapp
spec:
  replicas: 1
  selector:
    matchLabels:
      app: webapp
  template:
    metadata:
      labels:
        app: webapp
    spec:
      containers:
        - name: webapp
          image: public.ecr.aws/a5i1k0h2/arize-dev/webapp:v0.0.0
          ports:
            - containerPort: 5000
          # for convenience, check example.env
          envFrom:
            - secretRef:
                name: webapp-secrets
          resources:
            limits:
              memory: "2Gi"
              cpu: "2"
            requests:
              memory: "512Mi"
              cpu: "250m"
          readinessProbe:
            httpGet:
              path: /healthcheck
              port: 5000
            initialDelaySeconds: 10
            periodSeconds: 5
            timeoutSeconds: 3
            failureThreshold: 3
          livenessProbe:
            httpGet:
              path: /healthcheck
              port: 5000
            initialDelaySeconds: 60
            periodSeconds: 30
            timeoutSeconds: 3
            failureThreshold: 3
---
apiVersion: v1
kind: Service
metadata:
  name: webapp
spec:
  selector:
    app: webapp
  ports:
    - protocol: TCP
      port: 5000
      targetPort: 5000
  type: ClusterIP
