apiVersion: apps/v1
kind: Deployment
metadata:
  name: cflower
spec:
  replicas: 1
  selector:
    matchLabels:
      app: cflower
  template:
    metadata:
      labels:
        app: cflower
    spec:
      containers:
        - name: cflower
          image: public.ecr.aws/a5i1k0h2/arize-dev/webapp:v0.0.0
          command:
            - /bin/bash
            - -c
            - |
              celery --app make_celery.celery_app flower
          ports:
            - containerPort: 5555
          envFrom:
            - secretRef:
                name: celery-secrets
          resources:
            limits:
              memory: "512Gi"
              cpu: "500m"
            requests:
              memory: "64Mi"
              cpu: "50m"
          readinessProbe:
            httpGet:
              path: /
              port: 5555
            initialDelaySeconds: 10
            periodSeconds: 5
            timeoutSeconds: 3
            failureThreshold: 10
          livenessProbe:
            httpGet:
              path: /
              port: 5555
            initialDelaySeconds: 60
            periodSeconds: 30
            timeoutSeconds: 3
            failureThreshold: 3
---
apiVersion: v1
kind: Service
metadata:
  name: cflower
spec:
  selector:
    app: cflower
  ports:
    - protocol: TCP
      port: 5555
      targetPort: 5555
  type: ClusterIP
