services:

  db:
    image: postgres:latest
    container_name: webapp_db
    restart: always
    env_file:
      - .env
    ports:
      - "5432:5432"
#     volumes:
#       - webapp_db_data:/var/lib/postgresql/data

  # web:
  #   build: ./webapp
  #   container_name: webapp
  #   ports:
  #     - "5000:5000"
  #   depends_on:
  #     - db
  #   volumes:
  #     - ./webapp:/app

# volumes:
#   webapp_db_data:
