name: Build & Push WebApp to ECR

on:
  workflow_dispatch:

jobs:
  push_to_ecr:
    name: Build & Push WebApp to ECR
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      - name: Set up Docker credential helpers
        run: |
          curl -L https://github.com/docker/docker-credential-helpers/releases/download/v0.9.3/docker-credential-pass-v0.9.3.linux-amd64 \
            -o /usr/local/bin/docker-credential-pass
          chmod +x /usr/local/bin/docker-credential-pass
          echo '{"credsStore": "pass"}' > ~/.docker/config.json
      - name: Set up Docker
        uses: docker/setup-docker-action@v4
        with:
          daemon-config: |
            {
              "features": {
                "containerd-snapshotter": true
              }
            }
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Amazon ECR
        run: |
          aws ecr-public get-login-password --region us-east-1 | docker login --username AWS --password-stdin public.ecr.aws

      - name: Build Docker Image
        run: |
          cd webapp && make rebuild

      - name: Push Docker Image to ECR
        run: |
          cd webapp && make ci-push
