name: Build & Push WebApp to ECR

on:
  push:
    branches:
      - main
    paths:
      - 'webapp/**'
  workflow_dispatch:

jobs:
  push_to_ecr:
    name: Build & Push WebApp to ECR
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      - name: Set up Docker
        uses: docker/setup-docker-action@v4
        with:
          daemon-config: |
            {
              "features": {
                "containerd-snapshotter": true
              }
            }
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Set up Docker Compose
        uses: docker/setup-compose-action@v1
        with:
          version: latest

      - name: Login to Amazon ECR Public
        id: login-ecr-public
        uses: aws-actions/amazon-ecr-login@v2
        with:
          registry-type: public

      - name: Get Build Info
        id: get_build_info
        run: |
          IMAGE_FULL_TAG=$(yq '.services.web.image' ./webapp/docker-compose.yaml)
          PLATFORMS=$(yq '.services.web.build.platforms | join(",")' ./webapp/docker-compose.yaml)
          echo "IMAGE_FULL_TAG=$IMAGE_FULL_TAG" >> $GITHUB_OUTPUT
          echo "PLATFORMS=$PLATFORMS" >> $GITHUB_OUTPUT

      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          context: ./webapp
          push: true
          load: true
          platforms: ${{ steps.get_build_info.outputs.PLATFORMS }}
          tags: ${{ steps.get_build_info.outputs.IMAGE_FULL_TAG }}
